name := "retail"
version := "1.0"
scalaVersion := "2.11.8"

libraryDependencies += "org.apache.spark" % "spark-core_2.11" % "2.2.0"
libraryDependencies += "org.apache.spark" % "spark-streaming_2.11" % "2.2.0"
libraryDependencies += "org.apache.spark" % "spark-streaming-flume_2.11" % "2.2.0"
libraryDependencies += "org.apache.spark" % "spark-streaming-flume-sink_2.11" % "2.2.0"
libraryDependencies += "org.scala-lang" % "scala-library" % "2.11.8"
libraryDependencies += "org.apache.commons" % "commons-lang3" % "3.5"
